name: build
on:
  push:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Get repo name
        id: get_repo
        run: echo ::set-output name=REPO::${GITHUB_REPOSITORY#*/}

      - name: Setup java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'

      - name: Build artefacts
        run: |
          gradle build --no-daemon
          mkdir data
          cp ./build/libs/${GITHUB_REPOSITORY#*/}-*.jar ./data/app.jar
          echo "Branch: ${{ github.ref}}"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: ${{steps.get_repo.outputs.REPO}}
          path: ./data/app.jar

## Uncomment to trigger deploy to alpha when pull request
## Use for development. For prod use "Start publish workflow"
#      - name: Start publish and deploy to ALPHA workflow
#        if: startsWith(github.event.head_commit.message, 'Merge pull request')
#        uses: peter-evans/repository-dispatch@v1
#        with:
#          token: ${{ secrets.GITHUBACTION_TOKEN }}
#          repository: ${{ github.repository }}
#          event-type: trigger-to-publish-deploy-alpha

# Trigger a build and publish image to ACR
      - name: Start publish workflow
        if: github.ref == 'refs/heads/main'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUBACTION_TOKEN }}
          repository: ${{ github.repository }}
          event-type: trigger-to-publish

